I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/dialogue.rpy", line 60, in script
    $renpy.say(u,_whisper("Hey there, what's your name?"))
  File "game/dialogue.rpy", line 60, in <module>
    $renpy.say(u,_whisper("Hey there, what's your name?"))
KeyError: u'ret'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/dialogue.rpy", line 60, in script
    $renpy.say(u,_whisper("Hey there, what's your name?"))
  File "C:\Users\CORVO\Downloads\renpy-7.3.2-sdk\renpy\ast.py", line 912, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\CORVO\Downloads\renpy-7.3.2-sdk\renpy\python.py", line 2004, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/dialogue.rpy", line 60, in <module>
    $renpy.say(u,_whisper("Hey there, what's your name?"))
  File "C:\Users\CORVO\Downloads\renpy-7.3.2-sdk\renpy\exports.py", line 1336, in say
    who(what, *args, **kwargs)
  File "C:\Users\CORVO\Downloads\renpy-7.3.2-sdk\renpy\character.py", line 1126, in __call__
    what = what_pattern.replace("[what]", sub(what, translate=True))
  File "C:\Users\CORVO\Downloads\renpy-7.3.2-sdk\renpy\character.py", line 1115, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "C:\Users\CORVO\Downloads\renpy-7.3.2-sdk\renpy\substitutions.py", line 253, in substitute
    s = formatter.vformat(s, (), kwargs)
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 563, in vformat
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 585, in _vformat
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 646, in get_field
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 605, in get_value
KeyError: u'ret'

Windows-8-6.2.9200
Ren'Py 7.3.2.320
checkOnMyHeart 1.0
Tue Jul 23 18:02:01 2019
